<?php
return [
    'default' => [
        'manage user',
            'create user',
            'edit user',
            'delete user',
            'manage company',
            'create company',
            'edit company',
            'delete company',
            'create language',
            'manage system settings',
            'manage stripe settings',
            'manage role',
            'create role',
            'edit role',
            'delete role',
            'manage permission',
            'create permission',
            'edit permission',
            'delete permission',
            'manage plan',
            'create plan',
            'edit plan',
            'manage order',
            'manage coupon',
            'create coupon',
            'edit coupon',
            'delete coupon',
    ],
];
